// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzdwAwNhRuHFvfiLHOuUFl3qOpBYKyVU',
    appId: '1:52238079867:web:1fcfb8bd1d7b69acfa4fde',
    messagingSenderId: '52238079867',
    projectId: 'chat-app-e6276',
    authDomain: 'chat-app-e6276.firebaseapp.com',
    storageBucket: 'chat-app-e6276.appspot.com',
    measurementId: 'G-7V547WGC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKzeufOaj4bUYb4_BLJngHiYfe0ZLR9k',
    appId: '1:52238079867:android:e8dc3b3151be9ee1fa4fde',
    messagingSenderId: '52238079867',
    projectId: 'chat-app-e6276',
    storageBucket: 'chat-app-e6276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mIUYOuNFwbD2BNwHcsvrb6-JXymyZdA',
    appId: '1:52238079867:ios:4e8471594ea1cd0cfa4fde',
    messagingSenderId: '52238079867',
    projectId: 'chat-app-e6276',
    storageBucket: 'chat-app-e6276.appspot.com',
    iosBundleId: 'com.example.defApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mIUYOuNFwbD2BNwHcsvrb6-JXymyZdA',
    appId: '1:52238079867:ios:9b7ecf3c8c91ec07fa4fde',
    messagingSenderId: '52238079867',
    projectId: 'chat-app-e6276',
    storageBucket: 'chat-app-e6276.appspot.com',
    iosBundleId: 'com.example.defApp.RunnerTests',
  );
}
